apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    app: udagram-api-user