apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-service
  labels:
    app: udagram-frontend
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    service: udagram-frontend