# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: ci

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  push:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-lastest
    steps:
      -
        name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push api-feed
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-api-feed
            push: true
            tags: shine102/udagram-api-feed:v1
      - 
        name: Build and push api-user
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-api-user
            push: true
            tags: shine102/udagram-api-user:v1
      - 
        name: Build and push frontend
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-frontend
            push: true
            tags: shine102/udagram-frontend:v1
      - 
        name: Build and push reverse-proxy
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-reverse-proxy
            push: true
            tags: shine102/udagram-reverse-proxy:v1